version: '3.2'

services:
  postgres:
    image: postgres
    hostname: db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: db
      POSTGRES_DB: Customers
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres

volumes:
  pgdata:
